version: '3.9'

services:
  server:
    container_name: server_container
    image: server-image
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - "3050:3050"
    command: npm run start
